import { GeneratorConfig } from "@/types/generator";

export const fuelBillConfig: GeneratorConfig = {
  slug: "fuel-bill",
  name: "Fuel Bill",
  title: "Fuel Bill Generator — Petrol & Diesel Receipt Maker",
  description:
    "Create realistic petrol, diesel, CNG and EV fuel receipts for all major pumps. Pick a template, theme and currency, add pump branding, and download a PDF in seconds.",
  icon: "fa-gas-pump",
  category: "Transportation & Travel",
  popular: true,
  hasThemes: true,
  hasCrumple: true,
  templates: [
    { id: "template-1", label: "Classic Receipt" },
    { id: "template-2", label: "Compact Slip" },
    { id: "template-3", label: "Detailed Invoice" },
    { id: "template-4", label: "Modern Card" },
    { id: "template-5", label: "Dot-Matrix" },
    { id: "template-6", label: "Tax Invoice" },
  ],
  fields: [
    // --- Fuel Station Details ---
    {
      name: "logo",
      label: "Fuel Company",
      type: "logo",
      group: "Fuel Station Details",
      logos: [
        { id: "iocl", label: "Indian Oil", src: "/brands/iocl.svg" },
        { id: "bpcl", label: "Bharat Petroleum", src: "/brands/bpcl.svg" },
        { id: "hpcl", label: "HP Oil", src: "/brands/hpcl.svg" },
        { id: "essar", label: "Essar Oil", src: "/brands/essar.svg" },
      ],
    },
    { name: "stationName", label: "Fuel Station Name", type: "text", group: "Fuel Station Details", placeholder: "Sri Sai Fuel Station" },
    { name: "stationAddress", label: "Fuel Station Address", type: "textarea", group: "Fuel Station Details", placeholder: "NH-48, Sector 21, Gurugram, Haryana" },
    { name: "rate", label: "Fuel Rate (per L)", type: "number", group: "Fuel Station Details", half: true, placeholder: "96.72" },
    { name: "amount", label: "Total Amount", type: "number", group: "Fuel Station Details", half: true, placeholder: "2000.00" },
    { name: "currency", label: "Currency", type: "currency", group: "Fuel Station Details", half: true },
    { name: "showBankImage", label: "Show bank/card logo", type: "toggle", group: "Fuel Station Details", half: true },

    // --- Transaction Information ---
    { name: "date", label: "Fuel Bill Date", type: "date", group: "Transaction Information", half: true },
    { name: "time", label: "Fuel Bill Time", type: "time", group: "Transaction Information", half: true },
    { name: "bayNo", label: "Bay Number", type: "text", group: "Transaction Information", half: true, placeholder: "02" },
    { name: "nozzleNo", label: "Nozzle Number", type: "text", group: "Transaction Information", half: true, placeholder: "04" },
    { name: "mobile", label: "Mobile Number", type: "text", group: "Transaction Information", half: true, placeholder: "98765 43210" },
    {
      name: "density",
      label: "Density (kg/m³)",
      type: "select",
      group: "Transaction Information",
      half: true,
      options: Array.from({ length: 31 }, (_, i) => {
        const v = String(740 + i);
        return { value: v, label: v };
      }),
    },
    { name: "dealerName", label: "Dealer Name", type: "text", group: "Transaction Information", half: true, placeholder: "R. Kumar" },
    { name: "telNo", label: "Tel Number", type: "text", group: "Transaction Information", half: true, placeholder: "0124-2200000" },
    { name: "fipNo", label: "FIP No", type: "text", group: "Transaction Information", half: true, placeholder: "FIP-12" },
    { name: "fccId", label: "FCC ID", type: "text", group: "Transaction Information", half: true, placeholder: "FCC-9920" },
    { name: "transactionId", label: "Transaction ID", type: "text", group: "Transaction Information", half: true, placeholder: "TXN8841920" },
    { name: "attendantId", label: "Attendant ID", type: "text", group: "Transaction Information", half: true, placeholder: "ATT-07" },

    // --- Customer Details ---
    { name: "customerName", label: "Customer Name", type: "text", group: "Customer Details", half: true, placeholder: "Amit Sharma" },
    { name: "vehicleNo", label: "Vehicle Number", type: "text", group: "Customer Details", half: true, placeholder: "HR26 DK 8337" },
    {
      name: "vehicleType",
      label: "Vehicle / Fuel Type",
      type: "select",
      group: "Customer Details",
      half: true,
      options: [
        { value: "Petrol", label: "Petrol" },
        { value: "Diesel", label: "Diesel" },
        { value: "CNG", label: "CNG" },
        { value: "Electric", label: "Electric" },
      ],
    },
    {
      name: "receiptType",
      label: "Receipt Type",
      type: "select",
      group: "Customer Details",
      half: true,
      options: [
        { value: "Physical", label: "Physical" },
        { value: "Digital", label: "Digital" },
        { value: "E-Receipt", label: "E-Receipt" },
      ],
    },
    { name: "txnStart", label: "Transaction Start", type: "time", group: "Customer Details", half: true },
    { name: "txnEnd", label: "Transaction End", type: "time", group: "Customer Details", half: true },
    {
      name: "presetType",
      label: "Preset Type",
      type: "select",
      group: "Customer Details",
      half: true,
      options: [
        { value: "Local", label: "Local" },
        { value: "Interstate", label: "Interstate" },
        { value: "Export", label: "Export" },
        { value: "Retail", label: "Retail" },
        { value: "Wholesale", label: "Wholesale" },
      ],
    },
    {
      name: "paymentMethod",
      label: "Payment Method",
      type: "select",
      group: "Customer Details",
      half: true,
      options: [
        { value: "Cash", label: "Cash" },
        { value: "Online", label: "Online" },
        { value: "Card", label: "Card" },
      ],
    },
    { name: "invoiceNo", label: "Invoice Number", type: "text", group: "Customer Details", half: true, placeholder: "INV-2026-0042" },
  ],
  defaults: {
    logo: "iocl",
    stationName: "Sri Sai Fuel Station",
    stationAddress: "NH-48, Sector 21, Gurugram, Haryana 122016",
    rate: "96.72",
    amount: "2000.00",
    currency: "INR",
    showBankImage: false,
    date: "",
    time: "",
    bayNo: "02",
    nozzleNo: "04",
    mobile: "98765 43210",
    density: "750",
    dealerName: "R. Kumar",
    telNo: "0124-2200000",
    fipNo: "FIP-12",
    fccId: "FCC-9920",
    transactionId: "TXN8841920",
    attendantId: "ATT-07",
    customerName: "Amit Sharma",
    vehicleNo: "HR26 DK 8337",
    vehicleType: "Petrol",
    receiptType: "Digital",
    txnStart: "",
    txnEnd: "",
    presetType: "Retail",
    paymentMethod: "Cash",
    invoiceNo: "INV-2026-0042",
  },
};
