import { GeneratorConfig } from "@/types/generator";

export const olaBillConfig: GeneratorConfig = {
  slug: "ola-bill",
  name: "Ola Bill",
  title: "Ola Bill Generator — Ride Receipt & Invoice Maker",
  description:
    "Create realistic Ola cab ride receipts and GST invoices online. Add trip, driver and fare details, pick a template and currency, and download a print-ready PDF in seconds.",
  icon: "fa-car",
  category: "Transportation & Travel",
  popular: false,
  hasThemes: false,
  hasCrumple: false,
  templates: [
    { id: "template-1", label: "Ride Receipt" },
    { id: "template-2", label: "Invoice" },
  ],
  fields: [
    // --- Trip Details ---
    { name: "crn", label: "CRN / Booking ID", type: "text", group: "Trip Details", half: true, placeholder: "CRN1234567890" },
    {
      name: "category",
      label: "Ride Category",
      type: "select",
      group: "Trip Details",
      half: true,
      options: [
        { value: "Mini", label: "Mini" },
        { value: "Sedan", label: "Sedan" },
        { value: "Prime", label: "Prime" },
        { value: "Prime SUV", label: "Prime SUV" },
        { value: "Auto", label: "Auto" },
      ],
    },
    { name: "riderName", label: "Rider Name", type: "text", group: "Trip Details", half: true, placeholder: "Amit Sharma" },
    { name: "driverName", label: "Driver Name", type: "text", group: "Trip Details", half: true, placeholder: "Ramesh Yadav" },
    { name: "vehicleNo", label: "Vehicle Number", type: "text", group: "Trip Details", half: true, placeholder: "KA 01 AB 4521" },
    { name: "distanceKm", label: "Distance (km)", type: "number", group: "Trip Details", half: true, placeholder: "12.4" },
    { name: "rideTimeMin", label: "Ride Time (min)", type: "number", group: "Trip Details", half: true, placeholder: "34" },
    { name: "date", label: "Ride Date", type: "date", group: "Trip Details", half: true },
    { name: "time", label: "Ride Time", type: "time", group: "Trip Details", half: true },
    { name: "pickup", label: "Pickup Location", type: "textarea", group: "Trip Details", placeholder: "Brigade Road, MG Road, Bengaluru 560001" },
    { name: "drop", label: "Drop Location", type: "textarea", group: "Trip Details", placeholder: "Kempegowda Intl. Airport, Devanahalli, Bengaluru 560300" },

    // --- Fare Breakdown ---
    { name: "baseFare", label: "Base Fare", type: "number", group: "Fare Breakdown", half: true, placeholder: "49.00" },
    { name: "rideTimeCharge", label: "Ride Time Charge", type: "number", group: "Fare Breakdown", half: true, placeholder: "34.00" },
    { name: "distanceCharge", label: "Distance Charge", type: "number", group: "Fare Breakdown", half: true, placeholder: "148.80" },
    { name: "accessFee", label: "Access / Convenience Fee", type: "number", group: "Fare Breakdown", half: true, placeholder: "10.00" },
    { name: "tax", label: "GST (5%)", type: "number", group: "Fare Breakdown", half: true, placeholder: "12.09" },
    { name: "currency", label: "Currency", type: "currency", group: "Fare Breakdown", half: true },
    {
      name: "paymentMethod",
      label: "Payment Method",
      type: "select",
      group: "Fare Breakdown",
      half: true,
      options: [
        { value: "Cash", label: "Cash" },
        { value: "Ola Money", label: "Ola Money" },
        { value: "UPI", label: "UPI" },
        { value: "Credit Card", label: "Credit Card" },
        { value: "Debit Card", label: "Debit Card" },
      ],
    },
  ],
  defaults: {
    crn: "CRN1234567890",
    category: "Sedan",
    riderName: "Amit Sharma",
    driverName: "Ramesh Yadav",
    vehicleNo: "KA 01 AB 4521",
    distanceKm: "12.4",
    rideTimeMin: "34",
    date: "",
    time: "",
    pickup: "Brigade Road, MG Road, Bengaluru 560001",
    drop: "Kempegowda Intl. Airport, Devanahalli, Bengaluru 560300",
    baseFare: "49.00",
    rideTimeCharge: "34.00",
    distanceCharge: "148.80",
    accessFee: "10.00",
    tax: "12.09",
    currency: "INR",
    paymentMethod: "UPI",
  },
};
