import { GeneratorConfig } from "@/types/generator";

export const uberBillConfig: GeneratorConfig = {
  slug: "uber-bill",
  name: "Uber Bill",
  title: "Uber Bill Generator — Ride Receipt & Trip Invoice Maker",
  description:
    "Create realistic Uber-style ride receipts and trip invoices in seconds. Add trip details, driver and fare breakup, pick a currency, and download a PDF that looks like the real app receipt.",
  icon: "fa-car-side",
  category: "Transportation & Travel",
  popular: false,
  hasThemes: false,
  hasCrumple: false,
  templates: [
    { id: "template-1", label: "Ride Receipt" },
    { id: "template-2", label: "Trip Invoice" },
  ],
  fields: [
    // --- Trip ---
    { name: "riderName", label: "Rider Name", type: "text", group: "Trip", half: true, placeholder: "Amit Sharma" },
    { name: "driverName", label: "Driver Name", type: "text", group: "Trip", half: true, placeholder: "Rakesh Yadav" },
    { name: "carModel", label: "Car Model", type: "text", group: "Trip", half: true, placeholder: "Maruti Suzuki Dzire" },
    { name: "plateNo", label: "Number Plate", type: "text", group: "Trip", half: true, placeholder: "DL 3C AB 1234" },
    { name: "tripId", label: "Trip ID", type: "text", group: "Trip", half: true, placeholder: "T-9F2A8C41" },
    {
      name: "rideType",
      label: "Ride Type",
      type: "select",
      group: "Trip",
      half: true,
      options: [
        { value: "UberGo", label: "UberGo" },
        { value: "Uber Premier", label: "Uber Premier" },
        { value: "Uber XL", label: "Uber XL" },
        { value: "Uber Auto", label: "Uber Auto" },
        { value: "Uber Moto", label: "Uber Moto" },
        { value: "Uber Intercity", label: "Uber Intercity" },
      ],
    },
    { name: "pickup", label: "Pickup Location", type: "text", group: "Trip", placeholder: "Cyber Hub, DLF Phase 2, Gurugram" },
    { name: "drop", label: "Drop Location", type: "text", group: "Trip", placeholder: "IGI Airport Terminal 3, New Delhi" },
    { name: "distanceKm", label: "Distance (km)", type: "number", group: "Trip", half: true, placeholder: "18.6" },
    { name: "durationMin", label: "Duration (min)", type: "number", group: "Trip", half: true, placeholder: "34" },
    { name: "date", label: "Trip Date", type: "date", group: "Trip", half: true },
    { name: "time", label: "Trip Time", type: "time", group: "Trip", half: true },

    // --- Fare ---
    { name: "baseFare", label: "Base Fare", type: "number", group: "Fare", half: true, placeholder: "55.00" },
    { name: "distanceFare", label: "Distance Charge", type: "number", group: "Fare", half: true, placeholder: "186.00" },
    { name: "timeFare", label: "Time Charge", type: "number", group: "Fare", half: true, placeholder: "34.00" },
    { name: "surge", label: "Surge / Peak", type: "number", group: "Fare", half: true, placeholder: "40.00" },
    { name: "bookingFee", label: "Booking Fee", type: "number", group: "Fare", half: true, placeholder: "10.00" },
    { name: "tax", label: "Taxes (GST)", type: "number", group: "Fare", half: true, placeholder: "16.25" },
    { name: "currency", label: "Currency", type: "currency", group: "Fare", half: true },
    { name: "paymentMethod", label: "Payment Method", type: "text", group: "Fare", half: true, placeholder: "Visa **** 4242" },
  ],
  defaults: {
    riderName: "Amit Sharma",
    driverName: "Rakesh Yadav",
    carModel: "Maruti Suzuki Dzire",
    plateNo: "DL 3C AB 1234",
    tripId: "T-9F2A8C41",
    rideType: "UberGo",
    pickup: "Cyber Hub, DLF Phase 2, Gurugram",
    drop: "IGI Airport Terminal 3, New Delhi",
    distanceKm: "18.6",
    durationMin: "34",
    date: "",
    time: "",
    baseFare: "55.00",
    distanceFare: "186.00",
    timeFare: "34.00",
    surge: "40.00",
    bookingFee: "10.00",
    tax: "16.25",
    currency: "INR",
    paymentMethod: "Visa **** 4242",
  },
};
