import { GeneratorConfig } from "@/types/generator";

export const wifiBillConfig: GeneratorConfig = {
  slug: "wifi-bill",
  name: "Wi-Fi Bill",
  title: "Wi-Fi Bill Generator",
  description:
    "Create realistic Wi-Fi / broadband plan receipts and invoices online. Fill in your provider, plan, speed and charges to generate a clean downloadable bill.",
  icon: "fa-network-wired",
  category: "Utilities & Services",
  popular: false,
  hasThemes: false,
  hasCrumple: false,
  templates: [
    { id: "template-1", label: "Receipt" },
    { id: "template-2", label: "Invoice" },
  ],
  fields: [
    // Plan
    {
      name: "providerName",
      label: "Provider Name",
      type: "text",
      group: "Plan",
      placeholder: "Jio Fiber",
    },
    {
      name: "customerName",
      label: "Customer Name",
      type: "text",
      group: "Plan",
      placeholder: "Rohan Mehta",
    },
    {
      name: "planName",
      label: "Plan Name",
      type: "text",
      group: "Plan",
      half: true,
      placeholder: "Gold Unlimited",
    },
    {
      name: "speed",
      label: "Speed",
      type: "text",
      group: "Plan",
      half: true,
      placeholder: "150 Mbps",
    },
    {
      name: "validFrom",
      label: "Valid From",
      type: "date",
      group: "Plan",
      half: true,
    },
    {
      name: "validTo",
      label: "Valid To",
      type: "date",
      group: "Plan",
      half: true,
    },
    // Charges
    {
      name: "amount",
      label: "Plan Amount",
      type: "number",
      group: "Charges",
      half: true,
      placeholder: "999",
    },
    {
      name: "tax",
      label: "Tax (GST 18%)",
      type: "number",
      group: "Charges",
      half: true,
      placeholder: "179.82",
    },
    {
      name: "currency",
      label: "Currency",
      type: "currency",
      group: "Charges",
      half: true,
    },
    {
      name: "invoiceNo",
      label: "Invoice No.",
      type: "text",
      group: "Charges",
      half: true,
      placeholder: "WIFI-2026-0148",
    },
    {
      name: "date",
      label: "Invoice Date",
      type: "date",
      group: "Charges",
      half: true,
    },
    {
      name: "paymentMethod",
      label: "Payment Method",
      type: "select",
      group: "Charges",
      half: true,
      options: [
        { value: "UPI", label: "UPI" },
        { value: "Credit Card", label: "Credit Card" },
        { value: "Debit Card", label: "Debit Card" },
        { value: "Net Banking", label: "Net Banking" },
        { value: "Auto Pay", label: "Auto Pay" },
        { value: "Cash", label: "Cash" },
      ],
    },
  ],
  defaults: {
    providerName: "Jio Fiber",
    customerName: "Rohan Mehta",
    planName: "Gold Unlimited",
    speed: "150 Mbps",
    validFrom: "",
    validTo: "",
    amount: "999",
    tax: "179.82",
    currency: "INR",
    invoiceNo: "WIFI-2026-0148",
    date: "",
    paymentMethod: "UPI",
  },
};
