export interface ToolItem {
  slug: string;
  name: string;
  icon: string; // Font Awesome solid class
  category: string;
  blurb: string;
  /** Longer sentence used for SEO meta description. */
  seo: string;
}

export const TOOL_CATEGORIES = [
  "GST & Tax",
  "Salary & Payroll",
  "HR & Workforce",
  "Restaurant & Food Business",
  "Business & Everyday",
] as const;

export const TOOLS: ToolItem[] = [
  // ── GST & Tax ────────────────────────────────────────────────────────────
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    icon: "fa-percent",
    category: "GST & Tax",
    blurb: "Add or remove GST with CGST, SGST and IGST breakup.",
    seo: "Free online GST calculator for India. Add or extract 5%, 12%, 18% or 28% GST with instant CGST, SGST and IGST breakup.",
  },
  {
    slug: "reverse-gst-calculator",
    name: "Reverse GST Calculator",
    icon: "fa-rotate-left",
    category: "GST & Tax",
    blurb: "Extract the base price and GST from a GST-inclusive amount.",
    seo: "Free reverse GST calculator. Work backwards from a GST-inclusive price to the original base amount and tax portion.",
  },
  {
    slug: "gst-invoice-value-calculator",
    name: "GST Invoice Value Calculator",
    icon: "fa-file-invoice",
    category: "GST & Tax",
    blurb: "Compute the total invoice value with GST and discounts.",
    seo: "Calculate total GST invoice value online with item price, quantity, discount and GST rate with full tax breakup.",
  },
  {
    slug: "gst-interest-calculator",
    name: "GST Interest Calculator",
    icon: "fa-hourglass-half",
    category: "GST & Tax",
    blurb: "Interest payable on late GST payment at 18%/24% p.a.",
    seo: "Free GST late payment interest calculator. Compute interest at 18% or 24% per annum on delayed GST payments by days of delay.",
  },
  {
    slug: "gst-composition-scheme-calculator",
    name: "GST Composition Scheme Calculator",
    icon: "fa-layer-group",
    category: "GST & Tax",
    blurb: "Check eligibility and tax under the composition scheme.",
    seo: "GST composition scheme calculator. Check turnover eligibility and compute composition tax for traders, manufacturers and restaurants.",
  },
  {
    slug: "gst-refund-calculator",
    name: "GST Refund Calculator",
    icon: "fa-hand-holding-dollar",
    category: "GST & Tax",
    blurb: "Estimate GST refunds for exports and inverted duty.",
    seo: "Estimate your GST refund online for zero-rated exports and inverted duty structure with the free GST refund calculator.",
  },
  {
    slug: "itc-calculator",
    name: "ITC Calculator",
    icon: "fa-arrow-right-arrow-left",
    category: "GST & Tax",
    blurb: "Net GST payable after Input Tax Credit set-off.",
    seo: "Free Input Tax Credit (ITC) calculator. Set off IGST, CGST and SGST credits against output liability to find net GST payable.",
  },
  {
    slug: "income-tax-calculator",
    name: "Income Tax Calculator",
    icon: "fa-building-columns",
    category: "GST & Tax",
    blurb: "Income tax for FY 2025-26 under old and new regimes.",
    seo: "Income tax calculator for FY 2025-26 (AY 2026-27). Compare tax under the old and new regime with slab-wise breakup and cess.",
  },
  {
    slug: "old-vs-new-tax-regime-calculator",
    name: "Old vs New Tax Regime Calculator",
    icon: "fa-scale-balanced",
    category: "GST & Tax",
    blurb: "Which regime saves you more tax? Compare side by side.",
    seo: "Compare old vs new income tax regime for FY 2025-26. Enter salary and deductions to see which regime gives lower tax.",
  },
  {
    slug: "advance-tax-calculator",
    name: "Advance Tax Calculator",
    icon: "fa-calendar-check",
    category: "GST & Tax",
    blurb: "Quarterly advance tax instalments for FY 2025-26.",
    seo: "Advance tax calculator for FY 2025-26 with the 15%, 45%, 75% and 100% quarterly instalment schedule.",
  },
  {
    slug: "capital-gains-tax-calculator",
    name: "Capital Gains Tax Calculator",
    icon: "fa-arrow-trend-up",
    category: "GST & Tax",
    blurb: "STCG/LTCG tax on equity, property and gold.",
    seo: "Capital gains tax calculator for India. Compute short term and long term capital gains tax on equity, property and gold.",
  },
  {
    slug: "tds-calculator",
    name: "TDS Calculator on Salary",
    icon: "fa-scissors",
    category: "GST & Tax",
    blurb: "Monthly TDS deduction on salary for FY 2025-26.",
    seo: "TDS on salary calculator for FY 2025-26. Estimate annual tax and the monthly TDS your employer should deduct.",
  },
  {
    slug: "tcs-calculator",
    name: "TCS Calculator",
    icon: "fa-cart-shopping",
    category: "GST & Tax",
    blurb: "Tax Collected at Source across common transaction types.",
    seo: "TCS calculator for FY 2025-26. Compute Tax Collected at Source on foreign remittance, car purchase, scrap and more.",
  },
  {
    slug: "professional-tax-calculator",
    name: "Professional Tax Calculator",
    icon: "fa-id-card",
    category: "GST & Tax",
    blurb: "State-wise Professional Tax on your monthly salary.",
    seo: "Professional tax calculator for Indian states. Find the monthly PT deduction on your salary in Maharashtra, Karnataka, WB and more.",
  },

  // ── Salary & Payroll ─────────────────────────────────────────────────────
  {
    slug: "ctc-calculator",
    name: "CTC Calculator",
    icon: "fa-sack-dollar",
    category: "Salary & Payroll",
    blurb: "Convert CTC to in-hand salary with a full breakup.",
    seo: "Free CTC to in-hand salary calculator. See basic, HRA, PF, professional tax and net monthly take-home from your CTC.",
  },
  {
    slug: "in-hand-salary-calculator",
    name: "In-Hand Salary Calculator",
    icon: "fa-wallet",
    category: "Salary & Payroll",
    blurb: "Monthly take-home pay after PF, PT and income tax.",
    seo: "In-hand salary calculator for India. Convert CTC or gross salary to monthly take-home after PF, professional tax and TDS.",
  },
  {
    slug: "salary-calculator",
    name: "Salary Calculator",
    icon: "fa-money-bill-wave",
    category: "Salary & Payroll",
    blurb: "Gross-to-net salary with standard Indian deductions.",
    seo: "Simple salary calculator for India. Compute net salary from gross with EPF, ESI and professional tax deductions.",
  },
  {
    slug: "salary-hike-calculator",
    name: "Salary Hike Calculator",
    icon: "fa-arrow-up-right-dots",
    category: "Salary & Payroll",
    blurb: "New salary after a hike, or hike % between two salaries.",
    seo: "Salary hike calculator. Find your new salary after a percentage increment or the hike percent between old and new pay.",
  },
  {
    slug: "salary-arrears-calculator",
    name: "Salary Arrears Calculator",
    icon: "fa-clock-rotate-left",
    category: "Salary & Payroll",
    blurb: "Arrears due for a revised salary applied retrospectively.",
    seo: "Salary arrears calculator. Compute arrears payable when a salary revision applies from a past month, with month-wise detail.",
  },
  {
    slug: "salary-slip-generator",
    name: "Salary Slip Generator",
    icon: "fa-file-lines",
    category: "Salary & Payroll",
    blurb: "Create a professional salary slip with auto-calculations.",
    seo: "Free salary slip generator for India. Enter earnings and deductions to produce a clean, printable monthly pay slip.",
  },
  {
    slug: "hra-calculator",
    name: "HRA Calculator",
    icon: "fa-house",
    category: "Salary & Payroll",
    blurb: "HRA exemption under Section 10(13A).",
    seo: "HRA exemption calculator under Section 10(13A). Enter basic, HRA received and rent paid to find the tax-free HRA.",
  },
  {
    slug: "lta-calculator",
    name: "LTA Calculator",
    icon: "fa-plane",
    category: "Salary & Payroll",
    blurb: "Leave Travel Allowance exemption under Section 10(5).",
    seo: "LTA exemption calculator under Section 10(5). Find how much of your Leave Travel Allowance claim is tax exempt.",
  },
  {
    slug: "pf-calculator",
    name: "PF Calculator",
    icon: "fa-piggy-bank",
    category: "Salary & Payroll",
    blurb: "EPF corpus at retirement with yearly projection.",
    seo: "EPF calculator with interest projection. Estimate your provident fund corpus at retirement from basic salary and contribution rate.",
  },
  {
    slug: "epf-withdrawal-calculator",
    name: "EPF Withdrawal Calculator",
    icon: "fa-money-bill-transfer",
    category: "Salary & Payroll",
    blurb: "Withdrawal amount and TDS on early EPF withdrawal.",
    seo: "EPF withdrawal calculator. Estimate the amount you receive on PF withdrawal and TDS applicable before 5 years of service.",
  },
  {
    slug: "nps-calculator",
    name: "NPS Calculator",
    icon: "fa-umbrella",
    category: "Salary & Payroll",
    blurb: "NPS corpus at 60 and estimated monthly pension.",
    seo: "NPS calculator. Project your National Pension System corpus at retirement and the monthly pension from annuity purchase.",
  },
  {
    slug: "esi-calculator",
    name: "ESI Calculator",
    icon: "fa-briefcase-medical",
    category: "Salary & Payroll",
    blurb: "Employee and employer ESI contributions.",
    seo: "ESI contribution calculator. Compute 0.75% employee and 3.25% employer ESI on gross wages and check eligibility.",
  },
  {
    slug: "gratuity-calculator",
    name: "Gratuity Calculator",
    icon: "fa-gift",
    category: "Salary & Payroll",
    blurb: "Gratuity payable based on last salary and service years.",
    seo: "Gratuity calculator per the Payment of Gratuity Act. 15/26 formula on last drawn basic + DA and completed years of service.",
  },
  {
    slug: "leave-encashment-calculator",
    name: "Leave Encashment Calculator",
    icon: "fa-umbrella-beach",
    category: "Salary & Payroll",
    blurb: "Value of unused earned leave at exit or retirement.",
    seo: "Leave encashment calculator. Compute the cash value of unused earned leave and the tax-exempt portion under Section 10(10AA).",
  },
  {
    slug: "statutory-bonus-calculator",
    name: "Statutory Bonus Calculator",
    icon: "fa-award",
    category: "Salary & Payroll",
    blurb: "Bonus under the Payment of Bonus Act (8.33%–20%).",
    seo: "Statutory bonus calculator under the Payment of Bonus Act. Compute minimum 8.33% and maximum 20% bonus on eligible salary.",
  },
  {
    slug: "labour-code-salary-structure-calculator",
    name: "Labour Code Salary Structure Calculator",
    icon: "fa-sitemap",
    category: "Salary & Payroll",
    blurb: "Restructure CTC with basic ≥ 50% per new labour codes.",
    seo: "New labour code salary structure calculator. See how a 50% basic wage rule changes PF, gratuity and take-home pay.",
  },

  // ── HR & Workforce ───────────────────────────────────────────────────────
  {
    slug: "cost-per-hire-calculator",
    name: "Cost Per Hire Calculator",
    icon: "fa-user-plus",
    category: "HR & Workforce",
    blurb: "Average cost of hiring a new employee.",
    seo: "Cost per hire calculator. Add internal and external recruiting costs and divide by hires to benchmark your hiring spend.",
  },
  {
    slug: "employee-cost-calculator",
    name: "Employee Cost Calculator",
    icon: "fa-user-tie",
    category: "HR & Workforce",
    blurb: "True annual cost of an employee beyond CTC.",
    seo: "Employee cost calculator for India. Total cost of employment including CTC, employer PF, ESI, gratuity and overheads.",
  },
  {
    slug: "employee-turnover-cost-calculator",
    name: "Employee Turnover Cost Calculator",
    icon: "fa-people-arrows",
    category: "HR & Workforce",
    blurb: "What attrition really costs your company each year.",
    seo: "Employee turnover cost calculator. Estimate annual attrition cost from headcount, turnover rate and replacement cost per exit.",
  },
  {
    slug: "fnf-calculator",
    name: "FnF Calculator",
    icon: "fa-handshake",
    category: "HR & Workforce",
    blurb: "Full & final settlement: dues, leave, gratuity, recovery.",
    seo: "Full and final settlement calculator. Compute pending salary, leave encashment, bonus and notice recovery for an exiting employee.",
  },
  {
    slug: "maternity-leave-calculator",
    name: "Maternity Leave Calculator",
    icon: "fa-baby",
    category: "HR & Workforce",
    blurb: "Leave duration and paid benefit under the Maternity Act.",
    seo: "Maternity leave calculator per the Maternity Benefit Act. 26 weeks of paid leave, start-date planning and benefit amount.",
  },
  {
    slug: "minimum-wage-calculator",
    name: "Minimum Wage Calculator",
    icon: "fa-scale-unbalanced",
    category: "HR & Workforce",
    blurb: "Compare pay against state minimum wage rates.",
    seo: "Minimum wage calculator for India. Check whether a monthly or daily wage meets indicative state minimum wage levels.",
  },
  {
    slug: "notice-period-calculator",
    name: "Notice Period Calculator",
    icon: "fa-door-open",
    category: "HR & Workforce",
    blurb: "Notice pay or recovery for shortfall in notice served.",
    seo: "Notice period calculator. Compute notice pay payable or recoverable based on salary, notice required and notice served.",
  },
  {
    slug: "overtime-calculator",
    name: "Overtime Calculator",
    icon: "fa-stopwatch",
    category: "HR & Workforce",
    blurb: "Overtime pay at single or double the hourly rate.",
    seo: "Overtime pay calculator for India. Compute OT wages at 1x or 2x hourly rate from monthly salary and overtime hours.",
  },
  {
    slug: "work-hours-calculator",
    name: "Work Hours Calculator",
    icon: "fa-business-time",
    category: "HR & Workforce",
    blurb: "Total hours worked from in/out times, minus breaks.",
    seo: "Work hours calculator. Add daily in and out times, subtract breaks and total your weekly working hours and overtime.",
  },

  // ── Restaurant & Food Business ───────────────────────────────────────────
  {
    slug: "food-cost-calculator",
    name: "Food Cost Calculator",
    icon: "fa-utensils",
    category: "Restaurant & Food Business",
    blurb: "Food cost % and COGS for your restaurant.",
    seo: "Restaurant food cost calculator. Compute food cost percentage and cost of goods sold from inventory and sales.",
  },
  {
    slug: "recipe-costing-calculator",
    name: "Recipe Costing Calculator",
    icon: "fa-bowl-food",
    category: "Restaurant & Food Business",
    blurb: "Exact cost to prepare a dish, ingredient by ingredient.",
    seo: "Recipe costing calculator. Add ingredients with quantity and price to get per-dish cost and suggested selling price.",
  },
  {
    slug: "menu-pricing-calculator",
    name: "Menu Pricing Calculator",
    icon: "fa-book-open",
    category: "Restaurant & Food Business",
    blurb: "Ideal menu price from dish cost and target margin.",
    seo: "Menu pricing calculator for restaurants. Price dishes from food cost and target food-cost percentage or gross margin.",
  },
  {
    slug: "food-waste-cost-calculator",
    name: "Food Waste Cost Calculator",
    icon: "fa-trash-arrow-up",
    category: "Restaurant & Food Business",
    blurb: "Annual money lost to kitchen food waste.",
    seo: "Food waste cost calculator for restaurants. Turn daily wastage into monthly and yearly losses and see savings potential.",
  },
  {
    slug: "restaurant-break-even-calculator",
    name: "Restaurant Break-Even Calculator",
    icon: "fa-chart-line",
    category: "Restaurant & Food Business",
    blurb: "Sales needed to cover fixed and variable costs.",
    seo: "Restaurant break-even calculator. Find monthly sales and covers needed to break even from fixed costs and margins.",
  },
  {
    slug: "restaurant-profit-margin-calculator",
    name: "Restaurant Profit Margin Calculator",
    icon: "fa-chart-pie",
    category: "Restaurant & Food Business",
    blurb: "Gross and net margin for your restaurant.",
    seo: "Restaurant profit margin calculator. Compute gross and net profit margins from revenue, COGS, labour and overheads.",
  },
  {
    slug: "restaurant-staff-cost-calculator",
    name: "Restaurant Staff Cost Calculator",
    icon: "fa-users",
    category: "Restaurant & Food Business",
    blurb: "Total labour cost and labour % of sales.",
    seo: "Restaurant staff cost calculator. Total monthly labour cost across roles and labour cost as a percentage of sales.",
  },
  {
    slug: "restaurant-startup-cost-calculator",
    name: "Restaurant Startup Cost Calculator",
    icon: "fa-store",
    category: "Restaurant & Food Business",
    blurb: "One-time and working capital to open a restaurant.",
    seo: "Restaurant startup cost calculator for India. Estimate total investment: deposit, interiors, kitchen, licenses and working capital.",
  },
  {
    slug: "restaurant-franchise-cost-calculator",
    name: "Restaurant Franchise Cost Calculator",
    icon: "fa-shop",
    category: "Restaurant & Food Business",
    blurb: "Investment and payback for a franchise outlet.",
    seo: "Restaurant franchise cost calculator. Estimate franchise fee, setup cost, royalty and simple payback period for an outlet.",
  },
  {
    slug: "swiggy-zomato-commission-calculator",
    name: "Swiggy & Zomato Commission Calculator",
    icon: "fa-motorcycle",
    category: "Restaurant & Food Business",
    blurb: "Net payout after aggregator commission, fees and GST.",
    seo: "Swiggy and Zomato commission calculator. See your net payout per order after commission, payment fees, GST and discounts.",
  },
  {
    slug: "table-turnover-calculator",
    name: "Table Turnover Rate Calculator",
    icon: "fa-chair",
    category: "Restaurant & Food Business",
    blurb: "How many times each table turns per service.",
    seo: "Table turnover rate calculator. Compute turns per table from parties served, table count and service period.",
  },
  {
    slug: "fssai-license-fee-calculator",
    name: "FSSAI License Fee Calculator",
    icon: "fa-certificate",
    category: "Restaurant & Food Business",
    blurb: "License type and government fee for your food business.",
    seo: "FSSAI license fee calculator. Find whether you need basic registration, state or central license and the yearly fee.",
  },

  // ── Business & Everyday ──────────────────────────────────────────────────
  {
    slug: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    icon: "fa-coins",
    category: "Business & Everyday",
    blurb: "Gross, operating and net margin from your numbers.",
    seo: "Profit margin calculator. Compute gross, operating and net profit margins and markup from cost and revenue.",
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    icon: "fa-tags",
    category: "Business & Everyday",
    blurb: "Sale price after discount, plus stacked discounts.",
    seo: "Discount calculator. Find final price after percentage or flat discounts, including double-discount deals, and total savings.",
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator & Bill Splitter",
    icon: "fa-receipt",
    category: "Business & Everyday",
    blurb: "Add a tip and split the bill among friends.",
    seo: "Tip calculator and bill splitter. Add a tip percentage to your bill and split the total evenly among any number of people.",
  },
];

export const toolBySlug = (slug: string) => TOOLS.find((t) => t.slug === slug);

export const toolsByCategory = (category: string) =>
  TOOLS.filter((t) => t.category === category);
